// ##########################################################################
// ### This file is generated by Build and Continuous Integration scripts ###
// ###   .github/workflows/BuildInfo.py for local development environment ###
// ###   .github/workflows/testbuildrelease.yml for CI environment        ###
// ### Changes will be overwritten on the next build                      ###
// ##########################################################################

#include "BuildInfo.h"

const BuildEnvironment BuildInfo::buildEnvironment{BuildEnvironment::local};
const BuildType BuildInfo::buildType{BuildType::development};
const int BuildInfo::mainVersionDigit   = 0;
const int BuildInfo::minorVersionDigit  = 0;
const int BuildInfo::patchVersionDigit  = 0;
const char* BuildInfo::lastCommitTag    = "b268e41";
const char* BuildInfo::buildTimeStamp   = "2024-Jun-26 09:39:54";
